"""Guideline composition and the ``<fastplace-guidelines>`` writer.

``compose_guidelines`` renders the framework-conventions digest injected
into the project's ``AGENTS.md``; ``write_guidelines`` installs it with
tag-replace semantics — an existing ``<fastplace-guidelines>`` block is
replaced in place (user content around it keeps its position), otherwise
the block is appended. Rewriting is idempotent.
"""

from __future__ import annotations

import datetime as _dt
import re
from pathlib import Path

GUIDELINES_TAG_START = "<fastplace-guidelines>"
GUIDELINES_TAG_END = "</fastplace-guidelines>"

_BLOCK_RE = re.compile(
    re.escape(GUIDELINES_TAG_START) + r".*?" + re.escape(GUIDELINES_TAG_END),
    re.DOTALL,
)


def compose_guidelines(*, root: Path, fastplace_version: str, app_name: str = "Fastplace") -> str:
    """Render the full guidelines digest for this project."""
    today = _dt.date.today().isoformat()
    body = _SECTIONS.format(
        app_name=app_name,
        version=fastplace_version,
        generated=today,
    )
    return f"{GUIDELINES_TAG_START}\n{body}\n\n{GUIDELINES_TAG_END}"


def write_guidelines(path: Path, guidelines: str) -> Path:
    """Install ``guidelines`` into ``path`` with tag-replace semantics.

    Accepts either the full tagged block from :func:`compose_guidelines` or
    bare markdown (which gets wrapped).
    """
    if not guidelines.strip():
        return path
    stripped = guidelines.strip()
    if not stripped.startswith(GUIDELINES_TAG_START):
        stripped = GUIDELINES_TAG_START + "\n" + stripped + "\n\n" + GUIDELINES_TAG_END
    path.parent.mkdir(parents=True, exist_ok=True)
    content = path.read_text() if path.exists() else ""

    start = content.find(GUIDELINES_TAG_START)
    end = content.rfind(GUIDELINES_TAG_END)
    if start != -1 and end != -1 and end >= start:
        # The tag is framework-owned. Replace from the first start tag
        # through the last end tag — this also heals files an earlier
        # buggy install double-wrapped. User content lives outside the
        # tags and keeps its position.
        content = content[:start] + stripped + content[end + len(GUIDELINES_TAG_END) :]
    else:
        trimmed = content.rstrip()
        separator = "\n\n" if trimmed else ""
        content = trimmed + separator + stripped

    if not content.endswith("\n"):
        content += "\n"
    path.write_text(content)
    return path


_SECTIONS = """\
# {app_name} Framework Guidelines

Generated by `fastplace mcp install` on {generated} for Fastplace {version}.
Re-run `fastplace mcp update` after upgrading to refresh this block.

## Foundation

- Fastplace is an opinionated, full-stack, AI-native web framework: an async
  Python 3.12+ backend (Starlette, Pydantic v2, SQLAlchemy 2.x wrapped by the
  Fastplace ORM) paired with React 18+ / Tailwind CSS / Vite through a
  server-driven SPA bridge.
- It is a modular monolith by default: one deployable unit, strictly bounded
  internal modules. SQLite works with zero configuration; PostgreSQL is
  recommended for production (and required for vector search); MySQL is
  supported; MongoDB via the document-database adapter.
- Background work runs on SAQ + Redis. AI orchestration uses OpenAI /
  Anthropic APIs, LiteLLM, and Instructor.

## HTTP Layer

- Routes live in `routes/web.py`, `routes/api.py`, and `routes/ai.py` and
  stay thin: they declare controllers, nothing else.
- Controllers return `render(request, component="Page/Name", props={{...}})`
  for pages (the SPA bridge) or plain data for JSON endpoints. Controllers
  never contain business logic.
- Domain logic belongs in `app/modules/<name>/services/`; data access in
  `app/modules/<name>/repositories/`; request validation in
  `app/http/requests/`. Flow: Controllers -> Services -> Repositories ->
  Models.

## Conventions

- Python: type hints everywhere, `mypy fastplace` must stay clean, format
  with `ruff format .` and lint with `ruff check .`.
- Module boundaries are a hard gate: `fastplace lint:modules` fails on
  cross-module imports; it also re-checks on every `app/` save during
  `fastplace run dev`.
- Keep `.env` out of version control; update `.env.example` in the same
  change when adding configuration.
- `storage/` and `public/build/` are runtime output — never hand-edit them.

## Testing

- Backend: pytest (`pytest`, single file `pytest tests/http/test_render.py`).
  Write tests first, keep the suite green.
- Frontend: vitest + testing-library (`npm run test:run`), colocated under
  `__tests__/`; end-to-end flows with Playwright (`npx playwright test`).
- Static analysis gates: `mypy fastplace`, `ruff check .`, and
  `npm run types` for the React side.

## Database

- Models are declarative Fastplace ORM classes; `fastplace make:model Name -m`
  creates the model plus an Alembic migration.
- Apply schema changes with `fastplace migrate`; roll back the latest batch
  with `fastplace migrate:rollback`; seed with `fastplace db:seed`.
- Push filtering, sorting, and aggregation into queries — avoid N+1 access
  patterns and never process unbounded datasets in application memory.

## React Bridge

- Pages are React components under `resources/js/pages/`, resolved by name
  from the backend payload and hydrated via `usePage().props` from
  `@fastplace/react`.
- Initial loads return full HTML with an embedded JSON payload; subsequent
  navigation sends `X-Fastplace-Request: true` and receives only updated
  props + component names — no REST/GraphQL layer for pages.
- Shared UI lives in `resources/js/components/`, layouts in
  `resources/js/layouts/`. Match the theme tokens in `resources/css/` for
  both light and dark mode.

## AI

- `@Tool(description=...)` from `fastplace.ai` converts a typed Python
  function into a JSON schema for LLM function calling.
- `Agent(model=..., system_prompt=..., tools=[...])` streams via
  `agent.stream_response(...)`; frontend hooks `useAIStream` / `useAgent`
  from `@fastplace/ai-react` consume the `/ai/*` SSE endpoints.
- Vector search: `VectorField` columns + `Model.vector_search()` on
  PostgreSQL with pgvector.

## CLI

- `fastplace run dev` — Uvicorn (reload) + Vite (HMR) together.
- `fastplace serve` — builds `public/build/` then runs the production
  multi-worker ASGI server.
- `fastplace make:controller|make:model|make:agent|make:page` scaffold from
  templates; `fastplace shell` opens an interactive shell preloaded with the
  app context.

## MCP

- This project ships the `fastplace-aibrain` MCP server: start it with
  `fastplace mcp start` (already wired into the agent configs on this
  machine by `fastplace mcp install`).
- Prefer its tools over shell equivalents: `database-schema` /
  `database-query` for schema-aware, read-only SQL; `application-info` for
  exact framework and package versions; `search-docs` for framework docs;
  `last-error` / `read-log-entries` for logs; `browser-logs` for console
  output captured from the running app.
- `record-rule` writes durable project rules into `.fastplace/rules/` —
  only when the user explicitly asks to record a rule.
- `tinker` executes Python against the app in an isolated subprocess; it is
  disabled unless `FASTPLACE_MCP_TINKER=1`.
"""
