"""Migration manager + database CLI tests — Alembic wrapped in Fastplace API."""

from __future__ import annotations

import sqlite3

import pytest
from typer.testing import CliRunner

from fastplace.cli import app as cli_app

runner = CliRunner()


@pytest.fixture()
def project(tmp_path, monkeypatch):
    """A scaffolded Fastplace project with one model and a seeder."""
    (tmp_path / "app" / "modules" / "blog" / "models").mkdir(parents=True)
    (tmp_path / "database" / "seeders").mkdir(parents=True)
    (tmp_path / "config").mkdir(parents=True)
    (tmp_path / "storage").mkdir()

    (tmp_path / "app" / "__init__.py").write_text("")
    (tmp_path / "app" / "modules" / "__init__.py").write_text("")
    (tmp_path / "app" / "modules" / "blog" / "__init__.py").write_text("")
    (tmp_path / "app" / "modules" / "blog" / "models" / "__init__.py").write_text("")
    (tmp_path / "app" / "modules" / "blog" / "models" / "post.py").write_text(
        "from fastplace.orm import Field, Model\n"
        "\n"
        "class Post(Model):\n"
        "    __tablename__ = 'posts'\n"
        "    id: int = Field(primary_key=True)\n"
        "    title: str\n"
        "    body: str = Field(text=True, default='')\n"
    )
    (tmp_path / "database" / "seeders" / "post_seeder.py").write_text(
        "from app.modules.blog.models.post import Post\n"
        "\n"
        "async def run():\n"
        "    await Post.create(title='seeded', body='hello')\n"
    )
    (tmp_path / "config" / "app.py").write_text("APP_NAME = 'TestApp'\n")

    db_file = tmp_path / "test.sqlite3"
    monkeypatch.setenv("DATABASE_URL", f"sqlite+aiosqlite:///{db_file}")
    monkeypatch.chdir(tmp_path)
    return tmp_path


def _rows(project, sql):
    conn = sqlite3.connect(project / "test.sqlite3")
    try:
        return conn.execute(sql).fetchall()
    finally:
        conn.close()


def test_db_configure_scaffolds_migrations(project):
    result = runner.invoke(cli_app, ["db:configure"])
    assert result.exit_code == 0, result.output
    assert (project / "database" / "migrations" / "env.py").exists()
    assert (project / "database" / "migrations" / "script.py.mako").exists()
    assert (project / "database" / "migrations" / "versions").is_dir()


def test_full_migrate_lifecycle(project):
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0

    made = runner.invoke(cli_app, ["make:migration", "create_posts_table"])
    assert made.exit_code == 0, made.output
    versions = list((project / "database" / "migrations" / "versions").glob("*.py"))
    assert len(versions) == 1
    source = versions[0].read_text()
    # Autogenerate picked up the posts table from the declared model.
    assert "create_table" in source
    assert "posts" in source

    migrated = runner.invoke(cli_app, ["migrate"])
    assert migrated.exit_code == 0, migrated.output
    assert _rows(project, "SELECT count(*) FROM posts") == [(0,)]

    rolled = runner.invoke(cli_app, ["migrate:rollback"])
    assert rolled.exit_code == 0, rolled.output
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='posts'") == [(0,)]

    # Re-migrate then seed.
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    seeded = runner.invoke(cli_app, ["db:seed"])
    assert seeded.exit_code == 0, seeded.output
    assert _rows(project, "SELECT title FROM posts") == [("seeded",)]


def test_rollback_reverts_the_last_batch(project):
    """migrate:rollback reverts everything the last `migrate` applied."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0

    # Batch 1: posts.
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0

    # Batch 2: comments (a second model + migration).
    comment_pkg = project / "app" / "modules" / "comment"
    (comment_pkg / "models").mkdir(parents=True)
    (comment_pkg / "__init__.py").write_text("")
    (comment_pkg / "models" / "__init__.py").write_text("")
    (comment_pkg / "models" / "comment.py").write_text(
        "from fastplace.orm import Field, Model\n"
        "\n"
        "class Comment(Model):\n"
        "    __tablename__ = 'comments'\n"
        "    id: int = Field(primary_key=True)\n"
        "    body: str = ''\n"
    )
    made_comments = runner.invoke(cli_app, ["make:migration", "create_comments_table"])
    assert made_comments.exit_code == 0, made_comments.output
    # Framework bookkeeping tables never leak into autogenerated diffs.
    second = sorted((project / "database" / "migrations" / "versions").glob("*.py"))[-1]
    assert "fastplace_migrations" not in second.read_text()

    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='comments'") == [(1,)]

    # First rollback reverts batch 2 only.
    assert runner.invoke(cli_app, ["migrate:rollback"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='comments'") == [(0,)]
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='posts'") == [(1,)]

    # Second rollback reverts batch 1.
    assert runner.invoke(cli_app, ["migrate:rollback"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='posts'") == [(0,)]


_HAND_WRITTEN = '''"""{name}

Revision ID: {rev}
Revises: {down}
"""
from alembic import op
import sqlalchemy as sa

revision: str = '{rev}'
down_revision = {down!r}
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('{table}',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'))


def downgrade() -> None:
    op.drop_table('{table}')
'''


def test_migrate_applies_pending_set_as_one_batch(project):
    """Multiple pending revisions applied by ONE `migrate` = one rollback batch."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    versions = project / "database" / "migrations" / "versions"
    (versions / "aaa1_first.py").write_text(
        _HAND_WRITTEN.format(name="first", rev="aaa1", down=None, table="batch_a")
    )
    (versions / "bbb2_second.py").write_text(
        _HAND_WRITTEN.format(name="second", rev="bbb2", down="aaa1", table="batch_b")
    )

    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='batch_a'") == [(1,)]
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='batch_b'") == [(1,)]

    # One rollback reverts the whole batch — both pending revisions.
    rolled = runner.invoke(cli_app, ["migrate:rollback"])
    assert rolled.exit_code == 0, rolled.output
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='batch_a'") == [(0,)]
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='batch_b'") == [(0,)]


def test_rollback_with_explicit_steps(project):
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0

    stepped = runner.invoke(cli_app, ["migrate:rollback", "--steps", "1"])
    assert stepped.exit_code == 0, stepped.output
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='posts'") == [(0,)]


def test_db_reset_rebuilds_from_scratch(project):
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0

    result = runner.invoke(cli_app, ["db:reset"])
    assert result.exit_code == 0, result.output

    assert _rows(project, "SELECT name FROM sqlite_master WHERE name='posts'") == [("posts",)]
    assert _rows(project, "SELECT title FROM posts") == [("seeded",)]


def test_make_model_scaffolds_file(project):
    result = runner.invoke(cli_app, ["make:model", "Comment", "--migration"])
    assert result.exit_code == 0, result.output
    model_file = project / "app" / "modules" / "comment" / "models" / "comment.py"
    assert model_file.exists()
    assert "class Comment(Model):" in model_file.read_text()
    versions = list((project / "database" / "migrations" / "versions").glob("*.py"))
    assert len(versions) == 1
    assert "comments" in versions[0].read_text()


def test_migration_status_without_migrations_dir(project):
    result = runner.invoke(cli_app, ["migration:status"])
    # Not an error — reports that migrations aren't configured yet.
    assert result.exit_code == 0


def test_make_migration_imports_custom_column_types(project):
    # VectorField serializes as fastplace.orm.types.VectorJSON in the
    # generated revision — without the import the migration can never run.
    (project / "app" / "modules" / "blog" / "models" / "note.py").write_text(
        "from fastplace.orm import Field, Model, VectorField\n"
        "\n"
        "class Note(Model):\n"
        "    __tablename__ = 'notes'\n"
        "    id: int = Field(primary_key=True)\n"
        "    body: str = ''\n"
        "    embedding: 'list[float] | None' = VectorField(dimensions=3)\n"
    )
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    made = runner.invoke(cli_app, ["make:migration", "add_notes"])
    assert made.exit_code == 0, made.output

    revision = next((project / "database" / "migrations" / "versions").glob("*.py"))
    source = revision.read_text()
    assert "fastplace.orm.types.VectorJSON()" in source
    assert "import fastplace.orm.types" in source

    migrated = runner.invoke(cli_app, ["migrate"])
    assert migrated.exit_code == 0, migrated.output
    assert _rows(project, "SELECT name FROM sqlite_master WHERE type='table' AND name='notes'")


def _render_item_from_template():
    """Extract the env template's _render_item hook for direct testing."""
    import re

    from fastplace.orm.migrations.manager import _TEMPLATES_DIR

    source = (_TEMPLATES_DIR / "env.py.tpl").read_text()
    match = re.search(r"\ndef _render_item\(.*?\n(?=\ndef |\nasync def )", source, re.S)
    assert match, "the env template must define _render_item"
    namespace: dict = {}
    exec(match.group(0), namespace)  # noqa: S102 - framework template under test
    return namespace["_render_item"]


def test_render_item_imports_third_party_user_defined_types():
    """pgvector's VECTOR is a UserDefinedType from a private module — the
    generated revision must reference (and import) the public package path."""
    pytest.importorskip("pgvector")
    from pgvector.sqlalchemy import Vector

    render = _render_item_from_template()

    class _Autogen:
        imports: set[str] = set()

    ctx = _Autogen()
    rendered = render("type", Vector(3), ctx)
    assert rendered == "pgvector.sqlalchemy.VECTOR(dim=3)"
    assert "import pgvector.sqlalchemy" in ctx.imports


def test_tracking_table_guard_emits_no_ddl_when_table_exists():
    """Steady-state migrate runs must issue no tracking DDL at all.

    ``CREATE TABLE IF NOT EXISTS`` answers with MariaDB NOTE 1050 whenever
    the table already exists, and asyncmy mirrors the note to stderr — so
    every migrate after the first printed noise. The inspector-guarded
    ensure must create the table once and then stay completely silent.
    """
    import sqlalchemy
    from sqlalchemy import event

    from fastplace.orm.migrations.manager import _ensure_tracking_table

    engine = sqlalchemy.create_engine("sqlite://")
    statements: list[str] = []

    @event.listens_for(engine, "before_cursor_execute")
    def _capture(conn, cursor, statement, parameters, context, executemany):
        statements.append(statement)

    with engine.begin() as conn:
        _ensure_tracking_table(conn)
    assert any("fastplace_migrations" in s for s in statements)  # created once

    statements.clear()
    with engine.begin() as conn:
        _ensure_tracking_table(conn)
    # Steady state: reflection probes are fine; DDL is not (each CREATE TABLE
    # IF NOT EXISTS would answer with a MariaDB NOTE on a real server).
    assert [s for s in statements if not s.startswith("PRAGMA")] == []


def test_migrate_bookkeeping_never_builds_a_sync_engine(project, monkeypatch):
    """Batch tracking rides the async engine — migrate must not require the
    sync drivers (psycopg2/pymysql) that the framework never ships."""
    import sqlalchemy

    def _boom(*args, **kwargs):
        raise AssertionError("sync create_engine must not be used by migrate")

    monkeypatch.setattr(sqlalchemy, "create_engine", _boom)
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    # The tracking bookkeeping also runs on rollback paths.
    assert runner.invoke(cli_app, ["migrate:rollback"]).exit_code == 0


def test_bookkeeping_reconciles_applied_but_untracked_revisions(project):
    """A crash between upgrade and bookkeeping must not shrink rollback batches:
    the next sync re-records every applied-but-untracked revision."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0

    # Simulate the crash window: the schema is applied but the batch table
    # lost the record.
    conn = sqlite3.connect(project / "test.sqlite3")
    try:
        conn.execute("DELETE FROM fastplace_migrations")
        conn.commit()
    finally:
        conn.close()

    # A second, independent migration followed by a batch rollback must
    # revert BOTH revisions — proving the lost record came back.
    # (The new module is discovered by the filesystem walk; already-imported
    # models stay cached so they are not defined twice in one MetaData.)
    (project / "app" / "modules" / "blog" / "models" / "tag.py").write_text(
        "from fastplace.orm import Field, Model\n"
        "\n"
        "class Tag(Model):\n"
        "    __tablename__ = 'tags'\n"
        "    id: int = Field(primary_key=True)\n"
        "    name: str\n"
    )
    assert runner.invoke(cli_app, ["make:migration", "add_tags"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM tags") == [(0,)]

    rolled = runner.invoke(cli_app, ["migrate:rollback"])
    assert rolled.exit_code == 0, rolled.output
    # Both revision tables are gone — the recovered batch reverted both.
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name IN ('posts','tags')") == [
        (0,)
    ]


def test_make_migration_empty_creates_a_hand_writable_skeleton(project):
    """--empty skips autogeneration — the developer writes upgrade()/downgrade()."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0

    made = runner.invoke(cli_app, ["make:migration", "backfill_post_slugs", "--empty"])
    assert made.exit_code == 0, made.output

    versions = list((project / "database" / "migrations" / "versions").glob("*.py"))
    assert len(versions) == 1
    source = versions[0].read_text()
    assert "backfill_post_slugs" in source
    # Empty skeleton: no autogenerated diff content, both hooks present.
    assert "create_table" not in source
    assert "def upgrade() -> None:" in source
    assert "def downgrade() -> None:" in source

    # The skeleton is immediately runnable — migrate applies it as a no-op.
    migrated = runner.invoke(cli_app, ["migrate"])
    assert migrated.exit_code == 0, migrated.output


def _read_env(path):
    from pathlib import Path

    env = Path(path)
    return env.read_text() if env.exists() else ""


def test_db_configure_with_driver_writes_the_env_block(project):
    result = runner.invoke(cli_app, ["db:configure", "postgresql"])
    assert result.exit_code == 0, result.output

    env = _read_env(project / ".env")
    assert "DATABASE_DRIVER=postgresql" in env
    assert "DATABASE_URL=postgresql+asyncpg://user:password@localhost/fastplace" in env


def test_db_configure_creates_env_from_example_when_missing(project):
    (project / ".env.example").write_text("APP_NAME=TestApp\nDATABASE_DRIVER=sqlite\n")

    result = runner.invoke(cli_app, ["db:configure", "mysql"])
    assert result.exit_code == 0, result.output

    env = _read_env(project / ".env")
    # .env was seeded from .env.example…
    assert "APP_NAME=TestApp" in env
    # …then the DATABASE_* block was switched to mysql (replaced in place,
    # never duplicated).
    assert "DATABASE_DRIVER=mysql" in env
    assert env.count("DATABASE_DRIVER=") == 1
    assert "DATABASE_URL=mysql+asyncmy://user:password@localhost/fastplace" in env


def test_db_configure_switching_drivers_replaces_not_duplicates(project):
    assert runner.invoke(cli_app, ["db:configure", "postgresql"]).exit_code == 0
    switched = runner.invoke(cli_app, ["db:configure", "sqlite"])
    assert switched.exit_code == 0, switched.output

    env = _read_env(project / ".env")
    assert env.count("DATABASE_DRIVER=") == 1
    assert env.count("DATABASE_URL=") == 1
    assert "DATABASE_DRIVER=sqlite" in env
    assert "sqlite+aiosqlite" in env


def test_db_configure_mongodb_writes_the_document_adapter_url(project):
    result = runner.invoke(cli_app, ["db:configure", "mongodb"])
    assert result.exit_code == 0, result.output

    env = _read_env(project / ".env")
    assert "MONGODB_URL=mongodb://localhost:27017/fastplace" in env


def test_db_configure_mongodb_says_migrations_stay_relational(project):
    """Mongo has no schema migrations — the scaffolded Alembic env targets
    DATABASE_URL. Saying nothing leaves users believing `migrate` shapes
    their Mongo database; it does not, and never will."""
    result = runner.invoke(cli_app, ["db:configure", "mongodb"])
    assert result.exit_code == 0, result.output
    assert "migrate" in result.output
    assert "Mongo" in result.output


def test_db_configure_keeps_env_example_in_sync(project):
    result = runner.invoke(cli_app, ["db:configure", "postgresql"])
    assert result.exit_code == 0, result.output

    example = _read_env(project / ".env.example")
    assert "DATABASE_DRIVER=" in example
    assert "DATABASE_URL=" in example
    assert "MONGODB_URL=" in example


def test_db_configure_without_a_driver_leaves_env_untouched(project):
    """Bare `db:configure` keeps its legacy meaning: scaffold migrations only."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0

    assert not (project / ".env").exists() or "DATABASE_DRIVER=postgresql" not in _read_env(
        project / ".env"
    )


def test_db_configure_rejects_unknown_drivers(project):
    result = runner.invoke(cli_app, ["db:configure", "oracle"])
    assert result.exit_code == 1
    assert "oracle" in result.output
    assert "DATABASE_DRIVER" not in _read_env(project / ".env")


def test_db_configure_refuses_to_clobber_a_custom_database_url(project):
    """A hand-configured connection string is never silently destroyed."""
    custom = "DATABASE_URL=postgresql+asyncpg://svc:secret@db.internal:5432/app\n"
    (project / ".env").write_text(custom)

    result = runner.invoke(cli_app, ["db:configure", "postgresql"])

    assert result.exit_code == 1
    assert custom in _read_env(project / ".env")  # untouched


def test_db_configure_force_replaces_custom_value_and_leaves_a_backup(project):
    custom = "DATABASE_URL=postgresql+asyncpg://svc:secret@db.internal:5432/app\n"
    (project / ".env").write_text(custom)

    result = runner.invoke(cli_app, ["db:configure", "postgresql", "--force"])

    assert result.exit_code == 0, result.output
    assert "user:password@localhost/fastplace" in _read_env(project / ".env")
    # The overwritten value stays recoverable outside version control.
    assert custom in _read_env(project / ".env.bak")


def test_db_configure_rewrites_every_duplicate_of_a_key(project):
    """dotenv resolves duplicate keys last-wins — a surviving stale second
    line would silently undo the switch while the CLI reports success."""
    (project / ".env").write_text(
        "DATABASE_URL=mysql+asyncmy://stale@localhost/old\n"
        "APP_NAME=TestApp\n"
        "DATABASE_URL=mysql+asyncmy://stale@localhost/old\n"
    )

    result = runner.invoke(cli_app, ["db:configure", "postgresql", "--force"])

    assert result.exit_code == 0, result.output
    env = _read_env(project / ".env")
    assert env.count("DATABASE_URL=") == 1
    assert "postgresql+asyncpg" in env
    assert "stale" not in env


def test_db_configure_placeholder_switch_needs_no_force(project):
    """Switching between known placeholder values stays friction-free."""
    assert runner.invoke(cli_app, ["db:configure", "postgresql"]).exit_code == 0
    switched = runner.invoke(cli_app, ["db:configure", "sqlite"])
    assert switched.exit_code == 0, switched.output
    assert "sqlite+aiosqlite" in _read_env(project / ".env")


def test_upsert_env_lines_trailing_newline_convention():
    from fastplace.cli.database import _upsert_env_lines

    # Non-empty output always carries exactly one trailing newline…
    assert _upsert_env_lines("APP_NAME=X\n", {"APP_NAME": "Y"}) == "APP_NAME=Y\n"
    assert _upsert_env_lines("APP_NAME=X", {"APP_NAME": "Y"}) == "APP_NAME=Y\n"
    # …and empty input degrades to the appended block, not a blank file.
    assert _upsert_env_lines("", {"A": "1"}) == "A=1\n"


def test_migration_pipeline_binds_async_drivers(project, monkeypatch):
    """Bare schemes (mysql://, postgresql://) must bind to asyncmy/asyncpg.

    The runtime DatabaseManager already does this; the migration pipeline
    must share the contract, or a CI-style bare-scheme URL crashes Alembic
    with ModuleNotFoundError (MySQLdb / psycopg2).
    """
    from fastplace.orm.migrations.manager import MigrationsManager

    manager = MigrationsManager(project)

    monkeypatch.setenv("DATABASE_URL", "postgresql://u:p@db:5432/app")
    assert manager._database_url() == "postgresql+asyncpg://u:p@db:5432/app"

    monkeypatch.setenv("DATABASE_URL", "mysql://u:p@db:3306/app")
    assert manager._database_url() == "mysql+asyncmy://u:p@db:3306/app"

    # Already-bound and unbound-but-non-relational URLs pass through untouched.
    monkeypatch.setenv("DATABASE_URL", "sqlite+aiosqlite:///./x.sqlite3")
    assert manager._database_url() == "sqlite+aiosqlite:///./x.sqlite3"


def test_env_template_binds_async_drivers(project):
    """The scaffolded env.py shares _database_url's contract — normalize
    before Alembic builds its engine."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    env_py = (project / "database" / "migrations" / "env.py").read_text()
    assert "normalize_database_url" in env_py


def test_config_version_locations_is_absolute(project, monkeypatch):
    """version_locations must resolve regardless of process CWD.

    A relative value resolves against the CWD alembic happens to run from —
    `fastplace new` autogenerates the users migration from the PARENT of the
    project directory, and there a relative path either finds nothing or, far
    worse, a stranger's revisions directory (an outer checkout's), which fails
    autogenerate with "Target database is not up to date."
    """
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0

    from pathlib import Path

    from fastplace.orm.migrations.manager import MigrationsManager

    manager = MigrationsManager(project)
    outside = Path(project / ".." / "elsewhere").resolve()
    outside.mkdir(exist_ok=True)
    monkeypatch.chdir(outside)

    cfg = manager._config()
    locations = cfg.get_main_option("version_locations")
    assert Path(locations).is_absolute(), locations
    assert Path(locations) == manager.versions_dir
