"""Migration manager + database CLI tests — Alembic wrapped in Fastplace API."""

from __future__ import annotations

import sqlite3

import pytest
from typer.testing import CliRunner

from fastplace.cli import app as cli_app

runner = CliRunner()


@pytest.fixture()
def project(tmp_path, monkeypatch):
    """A scaffolded Fastplace project with one model and a seeder."""
    (tmp_path / "app" / "modules" / "blog" / "models").mkdir(parents=True)
    (tmp_path / "database" / "seeders").mkdir(parents=True)
    (tmp_path / "config").mkdir(parents=True)
    (tmp_path / "storage").mkdir()

    (tmp_path / "app" / "__init__.py").write_text("")
    (tmp_path / "app" / "modules" / "__init__.py").write_text("")
    (tmp_path / "app" / "modules" / "blog" / "__init__.py").write_text("")
    (tmp_path / "app" / "modules" / "blog" / "models" / "__init__.py").write_text("")
    (tmp_path / "app" / "modules" / "blog" / "models" / "post.py").write_text(
        "from fastplace.orm import Field, Model\n"
        "\n"
        "class Post(Model):\n"
        "    __tablename__ = 'posts'\n"
        "    id: int = Field(primary_key=True)\n"
        "    title: str\n"
        "    body: str = Field(text=True, default='')\n"
    )
    (tmp_path / "database" / "seeders" / "post_seeder.py").write_text(
        "from app.modules.blog.models.post import Post\n"
        "\n"
        "async def run():\n"
        "    await Post.create(title='seeded', body='hello')\n"
    )
    (tmp_path / "config" / "app.py").write_text("APP_NAME = 'TestApp'\n")

    db_file = tmp_path / "test.sqlite3"
    monkeypatch.setenv("DATABASE_URL", f"sqlite+aiosqlite:///{db_file}")
    monkeypatch.chdir(tmp_path)
    return tmp_path


def _rows(project, sql):
    conn = sqlite3.connect(project / "test.sqlite3")
    try:
        return conn.execute(sql).fetchall()
    finally:
        conn.close()


def test_db_configure_scaffolds_migrations(project):
    result = runner.invoke(cli_app, ["db:configure"])
    assert result.exit_code == 0, result.output
    assert (project / "database" / "migrations" / "env.py").exists()
    assert (project / "database" / "migrations" / "script.py.mako").exists()
    assert (project / "database" / "migrations" / "versions").is_dir()


def test_full_migrate_lifecycle(project):
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0

    made = runner.invoke(cli_app, ["make:migration", "create_posts_table"])
    assert made.exit_code == 0, made.output
    versions = list((project / "database" / "migrations" / "versions").glob("*.py"))
    assert len(versions) == 1
    source = versions[0].read_text()
    # Autogenerate picked up the posts table from the declared model.
    assert "create_table" in source
    assert "posts" in source

    migrated = runner.invoke(cli_app, ["migrate"])
    assert migrated.exit_code == 0, migrated.output
    assert _rows(project, "SELECT count(*) FROM posts") == [(0,)]

    rolled = runner.invoke(cli_app, ["migrate:rollback"])
    assert rolled.exit_code == 0, rolled.output
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='posts'") == [(0,)]

    # Re-migrate then seed.
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    seeded = runner.invoke(cli_app, ["db:seed"])
    assert seeded.exit_code == 0, seeded.output
    assert _rows(project, "SELECT title FROM posts") == [("seeded",)]


def test_rollback_reverts_the_last_batch(project):
    """migrate:rollback reverts everything the last `migrate` applied."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0

    # Batch 1: posts.
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0

    # Batch 2: comments (a second model + migration).
    comment_pkg = project / "app" / "modules" / "comment"
    (comment_pkg / "models").mkdir(parents=True)
    (comment_pkg / "__init__.py").write_text("")
    (comment_pkg / "models" / "__init__.py").write_text("")
    (comment_pkg / "models" / "comment.py").write_text(
        "from fastplace.orm import Field, Model\n"
        "\n"
        "class Comment(Model):\n"
        "    __tablename__ = 'comments'\n"
        "    id: int = Field(primary_key=True)\n"
        "    body: str = ''\n"
    )
    made_comments = runner.invoke(cli_app, ["make:migration", "create_comments_table"])
    assert made_comments.exit_code == 0, made_comments.output
    # Framework bookkeeping tables never leak into autogenerated diffs.
    second = sorted((project / "database" / "migrations" / "versions").glob("*.py"))[-1]
    assert "fastplace_migrations" not in second.read_text()

    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='comments'") == [(1,)]

    # First rollback reverts batch 2 only.
    assert runner.invoke(cli_app, ["migrate:rollback"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='comments'") == [(0,)]
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='posts'") == [(1,)]

    # Second rollback reverts batch 1.
    assert runner.invoke(cli_app, ["migrate:rollback"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='posts'") == [(0,)]


_HAND_WRITTEN = '''"""{name}

Revision ID: {rev}
Revises: {down}
"""
from alembic import op
import sqlalchemy as sa

revision: str = '{rev}'
down_revision = {down!r}
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('{table}',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'))


def downgrade() -> None:
    op.drop_table('{table}')
'''


def test_migrate_applies_pending_set_as_one_batch(project):
    """Multiple pending revisions applied by ONE `migrate` = one rollback batch."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    versions = project / "database" / "migrations" / "versions"
    (versions / "aaa1_first.py").write_text(
        _HAND_WRITTEN.format(name="first", rev="aaa1", down=None, table="batch_a")
    )
    (versions / "bbb2_second.py").write_text(
        _HAND_WRITTEN.format(name="second", rev="bbb2", down="aaa1", table="batch_b")
    )

    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='batch_a'") == [(1,)]
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='batch_b'") == [(1,)]

    # One rollback reverts the whole batch — both pending revisions.
    rolled = runner.invoke(cli_app, ["migrate:rollback"])
    assert rolled.exit_code == 0, rolled.output
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='batch_a'") == [(0,)]
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='batch_b'") == [(0,)]


def test_rollback_with_explicit_steps(project):
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0

    stepped = runner.invoke(cli_app, ["migrate:rollback", "--steps", "1"])
    assert stepped.exit_code == 0, stepped.output
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name='posts'") == [(0,)]


def test_db_reset_rebuilds_from_scratch(project):
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0

    result = runner.invoke(cli_app, ["db:reset"])
    assert result.exit_code == 0, result.output

    assert _rows(project, "SELECT name FROM sqlite_master WHERE name='posts'") == [("posts",)]
    assert _rows(project, "SELECT title FROM posts") == [("seeded",)]


def test_make_model_scaffolds_file(project):
    result = runner.invoke(cli_app, ["make:model", "Comment", "--migration"])
    assert result.exit_code == 0, result.output
    model_file = project / "app" / "modules" / "comment" / "models" / "comment.py"
    assert model_file.exists()
    assert "class Comment(Model):" in model_file.read_text()
    versions = list((project / "database" / "migrations" / "versions").glob("*.py"))
    assert len(versions) == 1
    assert "comments" in versions[0].read_text()


def test_migration_status_without_migrations_dir(project):
    result = runner.invoke(cli_app, ["migration:status"])
    # Not an error — reports that migrations aren't configured yet.
    assert result.exit_code == 0


def test_make_migration_imports_custom_column_types(project):
    # VectorField serializes as fastplace.orm.types.VectorJSON in the
    # generated revision — without the import the migration can never run.
    (project / "app" / "modules" / "blog" / "models" / "note.py").write_text(
        "from fastplace.orm import Field, Model, VectorField\n"
        "\n"
        "class Note(Model):\n"
        "    __tablename__ = 'notes'\n"
        "    id: int = Field(primary_key=True)\n"
        "    body: str = ''\n"
        "    embedding: 'list[float] | None' = VectorField(dimensions=3)\n"
    )
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    made = runner.invoke(cli_app, ["make:migration", "add_notes"])
    assert made.exit_code == 0, made.output

    revision = next((project / "database" / "migrations" / "versions").glob("*.py"))
    source = revision.read_text()
    assert "fastplace.orm.types.VectorJSON()" in source
    assert "import fastplace.orm.types" in source

    migrated = runner.invoke(cli_app, ["migrate"])
    assert migrated.exit_code == 0, migrated.output
    assert _rows(project, "SELECT name FROM sqlite_master WHERE type='table' AND name='notes'")


def _render_item_from_template():
    """Extract the env template's _render_item hook for direct testing."""
    import re

    from fastplace.orm.migrations.manager import _TEMPLATES_DIR

    source = (_TEMPLATES_DIR / "env.py.tpl").read_text()
    match = re.search(r"\ndef _render_item\(.*?\n(?=\ndef |\nasync def )", source, re.S)
    assert match, "the env template must define _render_item"
    namespace: dict = {}
    exec(match.group(0), namespace)  # noqa: S102 - framework template under test
    return namespace["_render_item"]


def test_render_item_imports_third_party_user_defined_types():
    """pgvector's VECTOR is a UserDefinedType from a private module — the
    generated revision must reference (and import) the public package path."""
    pytest.importorskip("pgvector")
    from pgvector.sqlalchemy import Vector

    render = _render_item_from_template()

    class _Autogen:
        imports: set[str] = set()

    ctx = _Autogen()
    rendered = render("type", Vector(3), ctx)
    assert rendered == "pgvector.sqlalchemy.VECTOR(dim=3)"
    assert "import pgvector.sqlalchemy" in ctx.imports


def test_migrate_bookkeeping_never_builds_a_sync_engine(project, monkeypatch):
    """Batch tracking rides the async engine — migrate must not require the
    sync drivers (psycopg2/pymysql) that the framework never ships."""
    import sqlalchemy

    def _boom(*args, **kwargs):
        raise AssertionError("sync create_engine must not be used by migrate")

    monkeypatch.setattr(sqlalchemy, "create_engine", _boom)
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    # The tracking bookkeeping also runs on rollback paths.
    assert runner.invoke(cli_app, ["migrate:rollback"]).exit_code == 0


def test_bookkeeping_reconciles_applied_but_untracked_revisions(project):
    """A crash between upgrade and bookkeeping must not shrink rollback batches:
    the next sync re-records every applied-but-untracked revision."""
    assert runner.invoke(cli_app, ["db:configure"]).exit_code == 0
    assert runner.invoke(cli_app, ["make:migration", "create_posts_table"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0

    # Simulate the crash window: the schema is applied but the batch table
    # lost the record.
    conn = sqlite3.connect(project / "test.sqlite3")
    try:
        conn.execute("DELETE FROM fastplace_migrations")
        conn.commit()
    finally:
        conn.close()

    # A second, independent migration followed by a batch rollback must
    # revert BOTH revisions — proving the lost record came back.
    # (The new module is discovered by the filesystem walk; already-imported
    # models stay cached so they are not defined twice in one MetaData.)
    (project / "app" / "modules" / "blog" / "models" / "tag.py").write_text(
        "from fastplace.orm import Field, Model\n"
        "\n"
        "class Tag(Model):\n"
        "    __tablename__ = 'tags'\n"
        "    id: int = Field(primary_key=True)\n"
        "    name: str\n"
    )
    assert runner.invoke(cli_app, ["make:migration", "add_tags"]).exit_code == 0
    assert runner.invoke(cli_app, ["migrate"]).exit_code == 0
    assert _rows(project, "SELECT count(*) FROM tags") == [(0,)]

    rolled = runner.invoke(cli_app, ["migrate:rollback"])
    assert rolled.exit_code == 0, rolled.output
    # Both revision tables are gone — the recovered batch reverted both.
    assert _rows(project, "SELECT count(*) FROM sqlite_master WHERE name IN ('posts','tags')") == [
        (0,)
    ]
