"""MigrationsManager — Alembic wrapped in the Fastplace public API.

Projects keep migrations in ``database/migrations/`` (versions in
``database/migrations/versions/``); the framework owns the environment
template so async engines, model discovery, and SQLite batch mode work
without project boilerplate (blueprint §8).
"""

from __future__ import annotations

import io
import shutil
import sys
from contextlib import redirect_stdout
from pathlib import Path
from typing import Any

_TEMPLATES_DIR = Path(__file__).parent / "templates"


class MigrationsManager:
    """Programmatic Alembic access: scaffold, make, upgrade, downgrade, status."""

    def __init__(self, project_root: str | Path) -> None:
        self.root = Path(project_root).resolve()
        self.migrations_dir = self.root / "database" / "migrations"
        self.versions_dir = self.migrations_dir / "versions"

    # -- state -----------------------------------------------------------------
    @property
    def configured(self) -> bool:
        """True once ``db:configure`` has scaffolded the environment."""
        return (self.migrations_dir / "env.py").exists()

    def require_configured(self) -> None:
        if not self.configured:
            raise RuntimeError(
                "Migrations are not configured — run `fastplace db:configure` first."
            )

    # -- setup ------------------------------------------------------------------
    def scaffold(self) -> list[Path]:
        """Create the migrations environment from framework templates."""
        self.migrations_dir.mkdir(parents=True, exist_ok=True)
        self.versions_dir.mkdir(parents=True, exist_ok=True)

        created: list[Path] = []
        for template_name in ("env.py.tpl", "script.py.mako"):
            target = self.migrations_dir / template_name.replace(".tpl", "")
            if not target.exists():
                shutil.copyfile(_TEMPLATES_DIR / template_name, target)
                created.append(target)
        return created

    # -- alembic plumbing ---------------------------------------------------------
    def _config(self) -> Any:
        from alembic.config import Config

        cfg = Config()
        cfg.set_main_option("script_location", str(self.migrations_dir))
        # Absolute on purpose: a relative value resolves against whatever the
        # process CWD happens to be, so autogenerate run from outside the
        # project (e.g. `fastplace new` scaffolding from the parent dir) would
        # read a stranger's revisions directory.
        cfg.set_main_option("version_locations", str(self.versions_dir))
        # env.py resolves the URL from DATABASE_URL (env/config modules).
        self._ensure_project_importable()
        return cfg

    def _ensure_project_importable(self) -> None:
        root = str(self.root)
        if root not in sys.path:
            sys.path.insert(0, root)

    # -- operations ----------------------------------------------------------------
    def make(self, message: str = "auto") -> Path | None:
        """Autogenerate a revision from the declared models.

        The revision diffs inside the project-boot sandbox: models another
        project left mapped on the global metadata (an in-process CLI run,
        say) are evicted for the diff, so a revision belongs to exactly the
        project whose versions directory holds it — never a stranger's
        tables. Persist mode keeps this project's own registrations for the
        callers that read the metadata after.
        """
        from alembic import command

        from fastplace.orm.registry import project_boot_sandbox

        self.require_configured()
        with project_boot_sandbox(self.root, persist=True), redirect_stdout(io.StringIO()):
            command.revision(self._config(), message=message, autogenerate=True)
        revisions = sorted(self.versions_dir.glob("*.py"), key=lambda p: p.stat().st_mtime)
        return revisions[-1] if revisions else None

    def make_empty(self, message: str = "manual") -> Path | None:
        """Create an empty revision skeleton for hand-written schema changes.

        ``make --empty`` in CLI terms: upgrade()/downgrade() hooks with no
        autogenerated diff — data backfills and hand-tuned DDL live here.
        """
        from alembic import command

        self.require_configured()
        with redirect_stdout(io.StringIO()):
            command.revision(self._config(), message=message, autogenerate=False)
        revisions = sorted(self.versions_dir.glob("*.py"), key=lambda p: p.stat().st_mtime)
        return revisions[-1] if revisions else None

    def upgrade(self) -> bool:
        """Run all pending migrations (``alembic upgrade head``).

        Everything applied is recorded as one batch in the framework-managed
        ``fastplace_migrations`` table, so a subsequent ``downgrade()``
        without steps can revert exactly this batch.
        """
        from alembic import command

        self.require_configured()
        with redirect_stdout(io.StringIO()):
            command.upgrade(self._config(), "head")
        self._sync_tracking()
        return True

    def pretend(self) -> str:
        """Render the SQL for the pending migrations without applying them.

        Alembic offline mode (``upgrade --sql``). Offline mode cannot see
        the database, so the range is seeded from the live ``alembic_version``
        — the script covers exactly what ``migrate`` would run (``head``
        alone would re-render already-applied revisions from base).
        """
        from alembic import command

        self.require_configured()
        heads = _run_async(self._current_heads_async())
        revision = f"{heads[0]}:head" if len(heads) == 1 else "head"
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            command.upgrade(self._config(), revision, sql=True)
        return buffer.getvalue().strip()

    def downgrade(self, steps: int | str | None = None) -> bool:
        """Revert migrations.

        ``steps=None`` (the CLI default) reverts the *last batch* — every
        revision applied by the most recent ``migrate`` invocation. An integer
        reverts that many individual revisions. A string is a named target:
        ``"base"`` reverts the whole history (what ``migrate:reset`` and
        ``db:wipe`` build on — no rebuild, no seed).
        """
        from alembic import command

        self.require_configured()
        if isinstance(steps, str):
            target = steps
        else:
            count = steps if steps is not None else self._last_batch_size()
            target = f"-{max(1, count)}"
        with redirect_stdout(io.StringIO()):
            command.downgrade(self._config(), target)
        self._sync_tracking()
        return True

    def reset(self) -> bool:
        """Downgrade to base, rebuild to head — a full schema rebuild."""
        from alembic import command

        self.require_configured()
        self.downgrade("base")
        with redirect_stdout(io.StringIO()):
            command.upgrade(self._config(), "head")
        # The rebuild applied the whole history in this one invocation.
        self._sync_tracking()
        return True

    # -- batch tracking ------------------------------------------------------------
    # `migrate:rollback` reverts "the latest migration batch": every revision
    # applied by the most recent `migrate` run.
    # Alembic alone does not track invocation batches, so the framework keeps
    # a small bookkeeping table next to alembic_version. All bookkeeping rides
    # the configured async engine — sync drivers (psycopg2/pymysql) are never
    # required.

    def _database_url(self) -> str:
        from fastplace.config import config, load_env
        from fastplace.orm.manager import normalize_database_url

        # Belt-and-braces alongside the CLI group callback: a programmatic
        # caller (no CLI involved) still resolves the same DATABASE_URL the
        # running app sees. load_dotenv never overrides a real env var.
        load_env(self.root / ".env")
        # Bare schemes (mysql://, postgresql://) bind to the async driver —
        # the same contract as the runtime DatabaseManager, or Alembic would
        # reach for the sync drivers (MySQLdb / psycopg2) that are not installed.
        raw = str(config("DATABASE_URL", default="sqlite+aiosqlite:///./database.sqlite3"))
        return normalize_database_url(raw)

    async def _applied_revisions_async(self) -> set[str]:
        """Every applied revision — the full ancestor chain, not just the head.

        ``get_current_heads()`` returns only the head of each branch; a
        revision is applied iff it is an ancestor of a stored version, so we
        walk the script graph down from each stored version.
        """
        heads = await self._current_heads_async()
        if not heads:
            return set()
        from alembic.script import ScriptDirectory

        script = ScriptDirectory.from_config(self._config())
        applied: set[str] = set()
        for head in heads:
            # base="base" walks the full ancestor chain of `head`, inclusive.
            for rev in script.walk_revisions(base="base", head=head):
                applied.add(rev.revision)
        return applied

    async def _current_heads_async(self) -> list[str]:
        """The revisions stored in ``alembic_version`` (empty when unversioned)."""
        from alembic.runtime.migration import MigrationContext
        from sqlalchemy.ext.asyncio import create_async_engine

        engine = create_async_engine(self._database_url())
        try:
            async with engine.connect() as conn:
                return list(
                    await conn.run_sync(lambda c: MigrationContext.configure(c).get_current_heads())
                )
        finally:
            await engine.dispose()

    def _sync_tracking(self) -> None:
        """Align the batch table with alembic_version (reconciling both ways).

        Revisions no longer applied are forgotten; applied-but-untracked
        revisions (e.g. a crash between upgrade and bookkeeping) are recorded
        into the newest batch so rollback batches never silently shrink.
        """
        _run_async(self._sync_tracking_async())

    async def _sync_tracking_async(self) -> None:
        import datetime

        from sqlalchemy import text
        from sqlalchemy.ext.asyncio import create_async_engine

        applied = await self._applied_revisions_async()
        engine = create_async_engine(self._database_url())
        try:
            async with engine.begin() as conn:
                await conn.execute(
                    text(
                        "CREATE TABLE IF NOT EXISTS fastplace_migrations ("
                        "revision VARCHAR(255) PRIMARY KEY, "
                        "batch INTEGER NOT NULL, "
                        "applied_at VARCHAR(64) NOT NULL)"
                    )
                )
                rows = await conn.execute(text("SELECT revision FROM fastplace_migrations"))
                tracked = {row[0] for row in rows}
                stale = tracked - applied
                if stale:
                    await conn.execute(
                        text("DELETE FROM fastplace_migrations WHERE revision = :r"),
                        [{"r": revision} for revision in sorted(stale)],
                    )
                missing = applied - tracked
                if missing:
                    result = await conn.execute(
                        text("SELECT COALESCE(MAX(batch), 0) FROM fastplace_migrations")
                    )
                    latest = int(result.scalar() or 0)
                    stamp = datetime.datetime.now(datetime.UTC).isoformat()
                    await conn.execute(
                        text(
                            "INSERT INTO fastplace_migrations (revision, batch, applied_at) "
                            "VALUES (:r, :b, :t)"
                        ),
                        [
                            {"r": revision, "b": latest + 1, "t": stamp}
                            for revision in sorted(missing)
                        ],
                    )
        finally:
            await engine.dispose()

    def _last_batch_size(self) -> int:
        """How many revisions the most recent `migrate` applied."""
        return _run_async(self._last_batch_size_async())

    async def _last_batch_size_async(self) -> int:
        from sqlalchemy import inspect, text
        from sqlalchemy.ext.asyncio import create_async_engine

        engine = create_async_engine(self._database_url())
        try:
            async with engine.connect() as conn:
                if not await conn.run_sync(lambda c: inspect(c).has_table("fastplace_migrations")):
                    return 1
                result = await conn.execute(
                    text("SELECT COALESCE(MAX(batch), 0) FROM fastplace_migrations")
                )
                latest = int(result.scalar() or 0)
                if latest == 0:
                    return 1
                result = await conn.execute(
                    text("SELECT COUNT(*) FROM fastplace_migrations WHERE batch = :b"),
                    {"b": latest},
                )
                return max(1, int(result.scalar() or 0))
        finally:
            await engine.dispose()

    def status(self) -> str:
        """Human-readable current revision + pending history."""
        from alembic import command
        from alembic.script import ScriptDirectory

        if not self.configured:
            return "Migrations are not configured. Run `fastplace db:configure`."

        cfg = self._config()
        script = ScriptDirectory.from_config(cfg)

        buffer = io.StringIO()
        with redirect_stdout(buffer):
            command.current(cfg)
        current_lines = buffer.getvalue().strip()

        head = script.get_current_head()
        revisions = list(script.walk_revisions())

        if not revisions:
            return "No migrations yet — create one with `fastplace make:migration <name>`."

        applied = _run_async(self._applied_revisions_async())

        lines = ["Migration status:"]
        for rev in revisions:
            # Rich would swallow a bare [applied] as a markup tag — escape
            # the brackets so the marker reaches the terminal verbatim.
            marker = "\\[applied]" if rev.revision in applied else "\\[ pending]"
            lines.append(f"  {marker} {rev.revision[:12]}  {rev.doc}")
        lines.append(f"  head: {head[:12] if head else '(none)'}")
        if current_lines:
            lines.append(f"  {current_lines}")
        return "\n".join(lines)


def _run_async(coro: Any) -> Any:
    """Run one coroutine on a throwaway loop (CLI paths are synchronous)."""
    import asyncio

    return asyncio.run(coro)


def _seeder_matches(stem: str, name: str) -> bool:
    """``user`` and ``user_seeder`` both name the ``user_seeder`` module."""
    return stem == name or stem == f"{name}_seeder"


def run_seeders(project_root: str | Path, seeder: str | None = None) -> list[str]:
    """Import and run ``database/seeders/*.py`` (module-level ``run()``).

    ``seeder`` narrows the run to a single module — its exact stem
    (``user_seeder``) or the name without the ``_seeder`` suffix (``user``).
    A name matching nothing raises ``ValueError`` listing the available
    seeders, so the CLI can refuse loudly instead of silently doing nothing.
    """
    import asyncio
    import importlib.util

    root = Path(project_root).resolve()
    seeders_dir = root / "database" / "seeders"
    files = sorted(seeders_dir.glob("*.py")) if seeders_dir.is_dir() else []
    files = [file for file in files if not file.name.startswith("_")]

    if seeder is not None:
        selected = [file for file in files if _seeder_matches(file.stem, seeder)]
        if not selected:
            available = ", ".join(file.stem for file in files) or "(none found)"
            raise ValueError(f"no seeder matches {seeder!r} — available: {available}")
        files = selected

    root_str = str(root)
    if root_str not in sys.path:
        sys.path.insert(0, root_str)

    ran: list[str] = []
    for file in files:
        module_name = f"_fastplace_seeder_{file.stem}"
        spec = importlib.util.spec_from_file_location(module_name, file)
        if spec is None or spec.loader is None:  # pragma: no cover
            continue
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)
        run = getattr(module, "run", None)
        if run is None:
            continue
        asyncio.run(run())
        ran.append(file.stem)
    return ran
